future: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  fenced_code_blocks: true

defaults:
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "default"

collections:
  blogs:
    output: true
    permalink: /blog/:slug.html
  research:
    output: true
    permalink: /research/:slug.html
  projects:
    output: true
    permalink: /projects/:slug.html

